import type { Metadata } from "next";
import { Hero } from "@/components/Hero";

export const metadata: Metadata = { title: "Event Management Services in Kanpur, Lucknow & Gorakhpur", description: "Explore Oryzene's wedding, corporate, birthday, esports, gaming, concert and live show event management services across Kanpur, Lucknow and Gorakhpur." };

const services = [
  { number: "01", title: "Weddings", intro: "A wedding should feel like a beautiful version of your people, not a production borrowed from someone else.", copy: "We work with you from the first moodboard through the last baraat detail, shaping a celebration that has a clear rhythm. That means helping with venue shortlists, guest movement, decor direction, hospitality, artist coordination, food and the run of show. Our team is comfortable in the details that make a day feel easy: a welcome that does not bottleneck, family photographs that stay on time, and a stage that looks as good from the back row as it does in the album. Whether you are planning an intimate gathering in Kanpur, a refined Lucknow wedding or a larger family celebration in Gorakhpur, we bring a grounded local network and one calm point of contact." },
  { number: "02", title: "Corporate Events", intro: "A strong corporate event respects the audience&apos;s time and gives the message a place to land.", copy: "Oryzene plans conferences, annual meets, product launches, dealer meets, award nights and team experiences with both brand and guest in mind. We translate the objective into a guest journey: registration, wayfinding, stage moments, content cues, food breaks and a close that people remember for the right reasons. Our production planning covers venue liaison, technical requirements, presenters, show calling, vendor management and on-ground execution. The result is an event that feels considered without feeling overworked, whether you are gathering a regional team in Lucknow or hosting a partner event in Kanpur." },
  { number: "03", title: "Birthday & Personal Celebrations", intro: "Milestones deserve more than a cake in the corner and a playlist on shuffle.", copy: "For birthdays, anniversaries, baby showers, reunions and family milestones, we build the atmosphere around the person or story being celebrated. We can take a loose idea and turn it into a theme with restraint, or start from a blank page and develop the setting, menu, entertainment and guest touches with you. We coordinate decorators, caterers, photographers, hosts, artists and venues so your family can be present instead of project-managing the evening. The details may be playful, elegant, high-energy or deeply personal; the planning stays clear." },
  { number: "04", title: "Esports & Gaming Events", intro: "Competition needs a stage, a system and an audience that can feel every round.", copy: "We bring event discipline to gaming communities, campus tournaments, brand activations and esports showcases. From bracket-friendly layouts and player check-in to broadcast-ready production, audience screens, shoutcasters, sponsors and prize moments, we plan the whole experience. The operational side matters as much as the spectacle: power, connectivity, timings, queue movement and contingency plans are designed before doors open. Oryzene helps teams create an event that feels authentic to players while remaining accessible and exciting for everyone watching." },
  { number: "05", title: "Concerts & Live Shows", intro: "Live events happen once. The plan has to be ready before the first note.", copy: "For concerts, cultural evenings, college shows and public programs, we coordinate the many moving parts that make a live show feel effortless. That includes artist liaison, venue and stage planning, sound and light requirements, backstage access, crew schedules, audience flow, hospitality, permissions support and the show call. We think about the experience from both sides of the barricade: a safe, clear arrival for guests and a focused environment for performers. From an intimate acoustic evening to a full campus or city program, Oryzene keeps the energy high and the operations steady." },
];

export default function ServicesPage() { return <main><Hero eyebrow="Our services" title="Events with a point of view." description="We bring structure to the exciting parts, care to the invisible parts and a local team to every part in between." /><div className="container-shell py-16 sm:py-24">{services.map((service) => <section key={service.number} className="grid gap-8 border-b border-[#28282e] py-12 first:pt-0 last:border-0 lg:grid-cols-[0.25fr_0.75fr] lg:gap-16"><div><span className="display-font text-5xl font-bold text-[#ff6a1f]">{service.number}</span></div><div><h2 className="section-title text-4xl">{service.title}</h2><p className="mt-6 max-w-2xl text-xl leading-8 text-[#f4f3ef]">{service.intro}</p><p className="mt-5 max-w-3xl text-base leading-8 text-[#9a9aa4]">{service.copy}</p></div></section>)}</div></main>; }
